// Code generated by goctl. DO NOT EDIT.
// Source: restrpc.proto

package server

import (
	"context"

	"github.com/yl3715a/testrpc/rpc/internal/logic/base"
	"github.com/yl3715a/testrpc/rpc/internal/svc"
	"github.com/yl3715a/testrpc/rpc/types/restrpc"
)

type RestrpcServer struct {
	svcCtx *svc.ServiceContext
	restrpc.UnimplementedRestrpcServer
}

func NewRestrpcServer(svcCtx *svc.ServiceContext) *RestrpcServer {
	return &RestrpcServer{
		svcCtx: svcCtx,
	}
}

func (s *RestrpcServer) InitDatabase(ctx context.Context, in *restrpc.Empty) (*restrpc.BaseResp, error) {
	l := base.NewInitDatabaseLogic(ctx, s.svcCtx)
	return l.InitDatabase(in)
}
