// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/yl3715a/testrpc/rpc/ent/predicate"
	"github.com/yl3715a/testrpc/rpc/ent/restrpc"
)

// RestrpcUpdate is the builder for updating Restrpc entities.
type RestrpcUpdate struct {
	config
	hooks    []Hook
	mutation *RestrpcMutation
}

// Where appends a list predicates to the RestrpcUpdate builder.
func (_u *RestrpcUpdate) Where(ps ...predicate.Restrpc) *RestrpcUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// Mutation returns the RestrpcMutation object of the builder.
func (_u *RestrpcUpdate) Mutation() *RestrpcMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RestrpcUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RestrpcUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RestrpcUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RestrpcUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *RestrpcUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(restrpc.Table, restrpc.Columns, sqlgraph.NewFieldSpec(restrpc.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{restrpc.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RestrpcUpdateOne is the builder for updating a single Restrpc entity.
type RestrpcUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RestrpcMutation
}

// Mutation returns the RestrpcMutation object of the builder.
func (_u *RestrpcUpdateOne) Mutation() *RestrpcMutation {
	return _u.mutation
}

// Where appends a list predicates to the RestrpcUpdate builder.
func (_u *RestrpcUpdateOne) Where(ps ...predicate.Restrpc) *RestrpcUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RestrpcUpdateOne) Select(field string, fields ...string) *RestrpcUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Restrpc entity.
func (_u *RestrpcUpdateOne) Save(ctx context.Context) (*Restrpc, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RestrpcUpdateOne) SaveX(ctx context.Context) *Restrpc {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RestrpcUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RestrpcUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *RestrpcUpdateOne) sqlSave(ctx context.Context) (_node *Restrpc, err error) {
	_spec := sqlgraph.NewUpdateSpec(restrpc.Table, restrpc.Columns, sqlgraph.NewFieldSpec(restrpc.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Restrpc.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, restrpc.FieldID)
		for _, f := range fields {
			if !restrpc.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != restrpc.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	_node = &Restrpc{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{restrpc.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
