// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// RestrpcsColumns holds the columns for the "restrpcs" table.
	RestrpcsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
	}
	// RestrpcsTable holds the schema information for the "restrpcs" table.
	RestrpcsTable = &schema.Table{
		Name:       "restrpcs",
		Columns:    RestrpcsColumns,
		PrimaryKey: []*schema.Column{RestrpcsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		RestrpcsTable,
	}
)

func init() {
}
