// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.2
// source: restrpc.proto

package restrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Restrpc_InitDatabase_FullMethodName = "/restrpc.Restrpc/initDatabase"
)

// RestrpcClient is the client API for Restrpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RestrpcClient interface {
	// group: base
	InitDatabase(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*BaseResp, error)
}

type restrpcClient struct {
	cc grpc.ClientConnInterface
}

func NewRestrpcClient(cc grpc.ClientConnInterface) RestrpcClient {
	return &restrpcClient{cc}
}

func (c *restrpcClient) InitDatabase(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*BaseResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BaseResp)
	err := c.cc.Invoke(ctx, Restrpc_InitDatabase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RestrpcServer is the server API for Restrpc service.
// All implementations must embed UnimplementedRestrpcServer
// for forward compatibility.
type RestrpcServer interface {
	// group: base
	InitDatabase(context.Context, *Empty) (*BaseResp, error)
	mustEmbedUnimplementedRestrpcServer()
}

// UnimplementedRestrpcServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRestrpcServer struct{}

func (UnimplementedRestrpcServer) InitDatabase(context.Context, *Empty) (*BaseResp, error) {
	return nil, status.Error(codes.Unimplemented, "method InitDatabase not implemented")
}
func (UnimplementedRestrpcServer) mustEmbedUnimplementedRestrpcServer() {}
func (UnimplementedRestrpcServer) testEmbeddedByValue()                 {}

// UnsafeRestrpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RestrpcServer will
// result in compilation errors.
type UnsafeRestrpcServer interface {
	mustEmbedUnimplementedRestrpcServer()
}

func RegisterRestrpcServer(s grpc.ServiceRegistrar, srv RestrpcServer) {
	// If the following call panics, it indicates UnimplementedRestrpcServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Restrpc_ServiceDesc, srv)
}

func _Restrpc_InitDatabase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RestrpcServer).InitDatabase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Restrpc_InitDatabase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RestrpcServer).InitDatabase(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Restrpc_ServiceDesc is the grpc.ServiceDesc for Restrpc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Restrpc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "restrpc.Restrpc",
	HandlerType: (*RestrpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "initDatabase",
			Handler:    _Restrpc_InitDatabase_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "restrpc.proto",
}
