// Code generated by goctl. DO NOT EDIT.
// Source: restrpc.proto

package restrpcclient

import (
	"context"

	"github.com/yl3715a/testrpc/rpc/types/restrpc"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BaseIDInt32Resp  = restrpc.BaseIDInt32Resp
	BaseIDInt64Resp  = restrpc.BaseIDInt64Resp
	BaseIDResp       = restrpc.BaseIDResp
	BaseIDStringResp = restrpc.BaseIDStringResp
	BaseIDUint32Resp = restrpc.BaseIDUint32Resp
	BaseResp         = restrpc.BaseResp
	BaseUUIDResp     = restrpc.BaseUUIDResp
	Empty            = restrpc.Empty
	IDInt32Req       = restrpc.IDInt32Req
	IDInt64Req       = restrpc.IDInt64Req
	IDReq            = restrpc.IDReq
	IDStringReq      = restrpc.IDStringReq
	IDUint32Req      = restrpc.IDUint32Req
	IDsInt32Req      = restrpc.IDsInt32Req
	IDsInt64Req      = restrpc.IDsInt64Req
	IDsReq           = restrpc.IDsReq
	IDsStringReq     = restrpc.IDsStringReq
	IDsUint32Req     = restrpc.IDsUint32Req
	PageInfoReq      = restrpc.PageInfoReq
	UUIDReq          = restrpc.UUIDReq
	UUIDsReq         = restrpc.UUIDsReq

	Restrpc interface {
		InitDatabase(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*BaseResp, error)
	}

	defaultRestrpc struct {
		cli zrpc.Client
	}
)

func NewRestrpc(cli zrpc.Client) Restrpc {
	return &defaultRestrpc{
		cli: cli,
	}
}

func (m *defaultRestrpc) InitDatabase(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*BaseResp, error) {
	client := restrpc.NewRestrpcClient(m.cli.Conn())
	return client.InitDatabase(ctx, in, opts...)
}
